### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by bypeter-ecxio** [carbon-design-system/carbon-for-ibm-dotcom-design-kit#49]
Thanks for your interest in the IBM.com Design kits!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from Carbon for IBM.com will reach out to you soon regarding your request for access.

> Which team are you on?
iX Studio Duesseldorf / Germany

> What experience are you designing for?
ix Dach webpage

> What platform is your experience on? (ie. Drupal, Wordpress, etc)
Drupal

> Please list a point of contact for:
Offering manager Markus Dietrich
Design lead Alexander de Babtistis
Development lead Michael Wolfram

> Any additional information you'd like to share about your project

**Comment by oliviaflory** [comment]
Hi @bypeter-ecxio would you mind sharing your IBM email so I can add you to the design kit folder?

Thank you!
