### ISSUE TITLE
[Design kit]: Update tag component

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom-design-kit#56]
Update the tag component to reflect the changes in this [feature request](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3669) planned for release in sprint 20.

Make sure all tags are set to Adjust content on resize

### Acceptance criteria
**Update all themes**
- [x] white
- [x] gray 10
- [ ] gray 90
- [ ] gray 100

**Comment by RobertaJHahn** [comment]
@oliviaflory I checked on the development status.  The dev work is in progress and should be finished by the end of this week.  I have moved this visual QA issue to sprint 20-21.
