### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by miketang32** [carbon-design-system/carbon-for-ibm-dotcom-design-kit#59]
Thanks for your interest in the `IBM.com Design Adopter Kit`!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from `Carbon for IBM.com` will reach out to you soon regarding your request for access.

> What is your email address?
mike.tang@ibm.com

> Which team are you on?
Systems. 

> What experience are you designing for?
Z Content Solutions

> What platform is your experience on? (ie. Drupal, Wordpress, etc)
Not sure

> Please list a point of contact for:
Offering manager
Design lead
Development lead: Danielle Atwood

> Please share any additional information you'd like to share about your project?
I'm a UX designer helping out with the content solutions pages. We've been looking to redesign the Z content solutions for a while now and I just found out about the carbon for ibm.com. I'm hoping this would be a useful asset for the redesign
https://www.ibm.com/support/z-content-solutions/

**Comment by oliviaflory** [comment]
Added to our box folder!
