### ISSUE TITLE
Design kit access request

### ISSUE THREAD

**Issue by pavolprok** [carbon-design-system/carbon-for-ibm-dotcom-design-kit#60]
Thanks for your interest in the `IBM.com Design Adopter Kit`!

We are in a closed adoption phase at the moment. Please answer the following questions to help us better understand your interest. Someone from `Carbon for IBM.com` will reach out to you soon regarding your request for access.

> What is your email address?
pavol_prok@sk.ibm.com

> Which team are you on?
IBM Marketing Studio, MSC

> What experience are you designing for?
Web

> What platform is your experience on? (ie. Drupal, Wordpress, etc)
Drupal, Hand coded

> Please list a point of contact for:
Offering manager
Nicoleta Costache
Design lead

Katie Andresen
Development lead

> Please share any additional information you'd like to share about your project?
From some unknown reason I lost my access to the folder. Can you please put me back in. Many thanks.

**Comment by oliviaflory** [comment]
added to box folder!
