### ISSUE TITLE
[Design kit]: Brief description

### ISSUE THREAD

**Issue by pavolprok** [carbon-design-system/carbon-for-ibm-dotcom-design-kit#61]
## Detailed description

Hello there, can you please guide me to the latest ibm.com Shell library, that contains the latest masthead and footer for all breakpoints? I do not see it in my Box folder  (Design Kit).

> What version of the Design kit are you using?

I have the latest version that I updated from the Box folder.

**Comment by oliviaflory** [comment]
Hi @pavolprok we are still evaluating how to update the masthead and footer symbols from our older design kit which you may have received it as an early adopter. We recently made some updates to the L1, which will be going live on our website documentation in the next few days, it's available in Storybook now. 

We do have the masthead and footer Sketch files available on Box and they should show the different breakpoints, I would recommend copy and pasting the masthead and footer examples into your file for now, you can also reference storybook to see how it behaves. 
https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/masthead
https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/footer

Please let me know if you have any questions
