### ISSUE TITLE
[Figma] Callout with media

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom-design-kit#73]
## Resources
* [Figma kit v2](https://www.figma.com/file/kPv0AmlXqKgrOoLbVLQ3fE/Carbon-for-IBM.com-(White-Theme)-v2-BETA?type=design&node-id=0%3A1&t=UFnGSoriRQd11ifD-1)
*  v2 design specs
* [Storybook v2 (with updates)](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-callout-with-media--default)

Like Callout quote, Callout with media gained additional color options in v2.

![Image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-design-kit/assets/15643582/2550b39e-ffc0-4591-a36c-1efa816c068c)

## v2 updates
- [ ] Updated color and type tokens to Carbon core v11.
- [ ] Additional color schemes for `blue`, `purple`, `cyan`, and `gray`. Some of the new color schemes use `callout-x` tokens in the IBM.com kit
- [ ] New color scheme default is `regular`

**Comment by oliviaflory** [comment]
Duplicate from Figma board
