### ISSUE TITLE
[Figma] Card group (to test with Content block)

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom-design-kit#76]
## Resources
* [Figma kit v2](https://www.figma.com/file/kPv0AmlXqKgrOoLbVLQ3fE/Carbon-for-IBM.com-(White-Theme)-v2-BETA?type=design&node-id=0%3A1&t=UFnGSoriRQd11ifD-1)
* [v1 design spec](https://www.figma.com/file/kT70Xx45YHEWmWi5Z3gH0r/Layout-component--card-group--visual-specs--v1.3.1?type=design&node-id=0%3A1&mode=design&t=lpYK8TKL9yEaSX2g-1)
* [Storybook v1](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-back-to-top--default)

Card group presents a collection of `card` components with multiple options for card type, grid mode, and offset. We're currently exploring a different styling for the CTA card that can appear in the Card group. This is a great case study for the grid modes Juan was exploring.

Note that in the live code, the height of each card is calculated based on the height of the tallest `card` in the collection.

## v2 updates
- [ ] Updated color and type tokens to Carbon v11.
- [ ] Added new border to align with Carbon v11 `tile` accessibility updates.

## Variant notes
- [ ] Grid modes available.
- [ ] Optional CTA card as the last in the set.
- [ ] Can add/remove `cards` in a row.
- [ ] Can change the card type – default, pictogram, static, card link
- [ ] Optional `card in card` can be displayed above the `card group` collection.

![Image](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-design-kit/assets/15643582/bf97e093-4b37-4a19-8729-9842b8fc4a0f)

**Comment by oliviaflory** [comment]
Question: should this component rely on the layout templates from the IBMer Experience Library to handle the various grid modes? 

Card group can accept ANY card type and can generally use any grid mode the designer wishes (other than static card)
- default
- + image
- pictogram
- logo
- static
